version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test


# orbs:
#   react-native: react-native-community/react-native@4.4.2
# https://circleci.com/developer/orbs/orb/react-native-community/react-native
